name: react-native-android-build-apk
on:
  push:
    branches:
      - main
jobs:
  build-and-release-android:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && chmod +x ./gradlew && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
      - name: Get version information
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: 'src/changelog.json'
          prefix: changelog
      - name: GitHub Release Action
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.changelog_changes_0_version }}
          name: ${{ env.changelog_changes_0_title }}
          artifacts: android/app/build/outputs/apk/release/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}