name: react-native-android-build-apk
on:
  push:
    branches:
      - main
jobs:
  build-and-release-android:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && chmod +x ./gradlew && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
      - name: GitHub Release Action
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.0
          body: "First Release"
          artifacts: android/app/build/outputs/apk/release/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}